---
- name: Create partition
  parted:
    device: "{{ disk_name }}"
    number: "{{ partition_number }}"
    state: present
    
- name: Create volume group
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ pv_name }}"
    

- name: Create logical volume
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: 100%FREE

- name: Create file system
  filesystem:
    fstype: "{{ file_system_type }}"
    dev: "/dev/{{ vg_name }}/{{ lv_name }}"

- name: Create mount point
  file:
    path: "{{ mount_point }}"
    state: directory

- name: Mount
  mount:
    path: "{{ mount_point }}"
    src: "/dev/{{ vg_name }}/{{ lv_name }}"
    fstype: "{{ file_system_type }}"
    state: mounted
